#
# Baseado em docker.yaml oficial do Verdaccio
# https://github.com/verdaccio/verdaccio/blob/master/packages/config/src/conf/docker.yaml
#

storage: /verdaccio/storage/data

plugins: /verdaccio/plugins

web:
  title: PipeDocs NPM Registry

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: 1000

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

server:
  keepAliveTimeout: 60
  trustProxy: true

middlewares:
  audit:
    enabled: true

log:
  type: stdout
  format: pretty
  level: http
